name: CI Bai 03

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu Github
        uses: actions/checkout@v4

      - name: Cai dat JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Chay Maven trong folder bai03
        run: mvn clean package
        working-directory: ./bai03

      - name: Luu file JAR sau khi build thành công
        uses: actions/upload-artifact@v4
        with:
          name: calculator-app-jar
          path: bai03/target/*.jar